# logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

---
spring:
  profiles: local

server:
  port: 8008

app:
  random:
    number: 7

---
spring:
  profiles: prod

server:
  port: 8009

app:
  random:
    number: 8