# logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR
aws:
  accessKeyId:
  secretKey:
  bucket:
  url: https://s3.amazonaws.com/

# increase the file size limit for multipart file upload
spring:
  http:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8008

---
spring:
  profiles: local

server:
  port: 8008

---
spring:
  profiles: prod

server:
  port: 8009
